### PR TITLE
Add support for python 3.9 - 3.10.

### PR DESCRIPTION
**Pull request by iksteen**
# Proposed Changes

I'm not even sure if you're willing to accept this, but after falling in love with its simplicity, I would like to this library in a project that runs on a Raspberry Pi. Unfortunately, the current version of raspbian, being based on Debian Bullseye, only comes with python 3.9.

The changes required are, in my opinion, minimal:
- Introduce a backport for `enum.StrEnum` for python < 3.11.
- Introduce a backport for `asyncio.timeout` for python < 3.11.
- Introduce a backport for `typing.Self` by importing it from `typing-extensions` instead.
- Switch union type annotations from `X | None` to `Optional[X]` (and introduce the appropriate ruff ignore).

Feel free to reject this, I can imagine not wanting to introduce these changes and maintaining them.

### CODE REVIEW

**Comment by joostlek** [comment]
I mean, I like seeing libraries with a legacy, but since I only started last summer, I don't have any. And since I only use them for HA, I never really need to support something more than the latest 2 or so :P.

I like to take the challenge. Although, I do want to move to AsyncGenerators in the future for getting albums, tracks, etc

**Comment by iksteen** [comment]
> I mean, I like seeing libraries with a legacy, but since I only started last summer, I don't have any. And since I only use them for HA, I never really need to support something more than the latest 2 or so :P.

Understandably so! Like I said, feel free to reject it because it *does* introduce a maintenance burden. I can just maintain my own fork or vendor it with some changes until Raspbian updates to a newer python version.

> I like to take the challenge. Although, I do want to move to AsyncGenerators in the future for getting albums, tracks, etc

Async generators have been supported since python 3.6, so unless there are some improvements in python 3.11+ specifically, that shouldn't be a problem I think?

**Comment by joostlek** [comment]
I am not completely up to date with what is introduced when haha

**Comment by joostlek** [comment]
In pyproject.toml we also have a mypy version it should use. Wondering what what it should be set to

**Pull request closed without merging**
